### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by akimd** [nemequ/icc-travis#15]
Hi,

Yes, I saw that the README does mention the fact that it no longer since September 2019, but let's have an issue so that if a fix is found, one can report it here.

Thanks for having maintained this very useful component.  Bison used to use it.

**Comment by akimd** [comment]
FTR, I had mentioned this on Intel's forum in April 2019 (https://software.intel.com/en-us/forums/intel-c-compiler/topic/564473).  There never was an answer.  That's sad.

**Comment by jeffhammond** [comment]
If you install the oneAPI beta (https://software.intel.com/en-us/oneapi/base-kit), it includes the Intel compiler.  You can install it with yum or apt (https://software.intel.com/en-us/articles/oneapi-repo-instructions).

The script works with some licenses.  I haven't had time to debug it, but it works with my license keys (which are unlimited).

**Comment by nemequ** [comment]
Thanks Jeff!  It works perfectly for me, and doesn't even seem to check for a license.  I don't know if that's intentional or not, but if not I hope nobody "fixes" it :)

I'll update the README at some point soon to describe what to do, but for now here is an example (modified [from SIMDe](https://github.com/nemequ/simde/blob/419edf2df5688e13d4ae3158cd0a1c5ccf642c01/.travis.yml#L109)):

```yaml
jobs:
  include:
  - name: icc
    install:
    - source /opt/intel/inteloneapi/compiler/latest/env/vars.sh
    addons:
      apt:
        sources:
        - sourceline: 'deb https://apt.repos.intel.com/oneapi all main'
          key_url: 'https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB'
        packages:
        - intel-oneapi-icc
```

I have a couple other entries in SIMDe to instruct the build system to use icc/icpc; you can't just set CC/CXX in the env section here (Travis will clobber them later), so I set `C_COMPILER` and `CXX_COMPILER` instead then just `export CC=C_COMPILER` and `export CXX=CXX_COMPILER` in my `before_install` section.  Just take a look at SIMDe, you should be able to figure it out, but if not I'm around for questions.
